name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          # - id: ubuntu-latest
          #   path: ./dist/linux/*.zip
          #   label: linux
          # - id: windows-latest
          #   path: ./dist/win32/*.zip
          #   label: windows
          - id: macos-latest
            path: ./dist/darwin/*.dmg
            label: mac
    runs-on: ${{ matrix.os.id }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - run: npm ci
      - run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os.label }}
          path: ${{ matrix.os.path }}
